FROM python:3.11.5-bullseye as base

RUN apt-get update && apt-get install -y \
    ffmpeg \
    curl

WORKDIR /app

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.cargo/bin:${PATH}"

RUN uv venv -p $(which python) .venv
RUN bash -c 'source .venv/bin/activate'

COPY src/frontend /app/frontend


RUN uv pip install -r /app/frontend/requirements.txt

WORKDIR /app/frontend

CMD ["/app/.venv/bin/python", "-m", "streamlit", "run", "app.py", "--server.port", "8080", "--server.enableCORS", "false", "--"]